### ISSUE TITLE
Define API types

### ISSUE THREAD

**Issue by ayanmallik** [hack4impact-uiuc/brink#10]
**Type**: full stack
**FOF**:  3

## Description
- Define types for various API requests/responses that are used populate election/candidate info
- Use those defined types to write a script that populates mock data that will be used for testing

### Step 1 - Read endpoint documentation to understand the structure of the API request/response
Example: https://developers.civicengine.com/docs/api/v1/get-elections

### Step 2 - Define Type for API Request/Response
![image](https://user-images.githubusercontent.com/45826922/153767126-18b3dc48-acff-4183-907d-d37bbddf6453.png)
![image](https://user-images.githubusercontent.com/45826922/153767159-589d6d9d-8466-4cd8-bb63-d633c38ccd1a.png)

## Todo

- [x] [Civic Engine - Elections](https://developers.civicengine.com/docs/api/v1/get-elections)
- [x] [Civic Engine - Positions](https://developers.civicengine.com/docs/api/v1/get-positions)
- [ ] [Google Civic](https://developers.google.com/civic-information/docs/v2)
- [ ] [Democracy Works](https://www.democracy.works/elections-api/)

## Learning Objectives
- TypeScript
- API's
