### ISSUE TITLE
🗳 Nearby Polling Locations

### ISSUE THREAD

**Issue by ayanmallik** [hack4impact-uiuc/brink#105]
**Type**: full stack
**FOF**:  3

## Description
- Display the nearby polling locations that the voter can visit
- Utilize Democracy Works/Google Civic API

## Screenshot
View:
<img width="618" alt="image" src="https://user-images.githubusercontent.com/45826922/165676192-35c7176e-f2fc-4095-980f-f923534f7d65.png">

Interface:
<img width="545" alt="image" src="https://user-images.githubusercontent.com/45826922/165676295-4d1eed96-49c6-4da7-98ce-4c2013b0157f.png">

## Todo

- [ ] Build a new page to display nearby polling locations
- [ ] Hook up one the link to the "Find my polling locations" button on the voting checklist
- [ ] Fetch and display the nearby polling locations from Democracy Works/Google Civic API

## Links
- [Figma](https://www.figma.com/file/6aJ3cfu2Yq5dxUQcNDkm6Y/%F0%9F%8E%A8-Brink-Designs?node-id=565%3A1390)
