### ISSUE TITLE
Populate mock data

### ISSUE THREAD

**Issue by ayanmallik** [hack4impact-uiuc/brink#15]
**Type**: full stack
**FOF**:  2

## Description
- Use those defined types from #10 to write a script that populates mock data that will be used for testing
 
### Step 1 - Write script using [faker-js](https://github.com/faker-js/faker) to populate mock data
![image](https://user-images.githubusercontent.com/45826922/153768999-3224f053-af9d-4782-ae06-5e16ab2c229f.png)

### Step 2 - Generate and validate mock data
```javascript
node generate-api.js
```
![image](https://user-images.githubusercontent.com/45826922/153769190-29f89644-60a1-46ff-8eb8-a17c589a7451.png)

## Todo

- [x] [Civic Engine - Elections](https://developers.civicengine.com/docs/api/v1/get-elections)
- [ ] [Civic Engine - Positions](https://developers.civicengine.com/docs/api/v1/get-positions)
- [ ] [Google Civic](https://developers.google.com/civic-information/docs/v2)
- [ ] [Democracy Works](https://www.democracy.works/elections-api/)

## Learning Objectives
- Faker-JS
- Data Infrastructure
