### ISSUE TITLE
🍽 Menu Tabs for search page

### ISSUE THREAD

**Issue by ayanmallik** [hack4impact-uiuc/brink#20]
**Type**: client
**FOF**:  2

## Description
- Implement the sticky menu tabs for the home page

## Screenshot
![image](https://user-images.githubusercontent.com/45826922/154396945-2f7d6ebd-cd6f-49fa-9abe-943451d1f14e.png)

## Todo

- [x] Import icons for the tab headers
- [x] Place the tab menu under the main navigation bar
- [x] Set the menu to sticky

## Links
- [Chakra UI - Tabs](https://chakra-ui.com/docs/disclosure/tabs)
- [Figma](https://www.figma.com/file/6aJ3cfu2Yq5dxUQcNDkm6Y/Brink-Designs?node-id=34%3A2)
