### ISSUE TITLE
🪗 Accordion component

### ISSUE THREAD

**Issue by ayanmallik** [hack4impact-uiuc/brink#22]
**Type**: client
**FOF**:  2

## Description
Implement and style a generic accordion component

## Screenshot
![image](https://user-images.githubusercontent.com/45826922/154408214-e86bc387-cbb1-40be-8656-b660b60a34dc.png)

## Todo

- [ ] Create a folder that stores generic UI components
- [ ] Implement the skeleton of the Accordion component
- [ ] Style the accordion to match the Figma

## Links
- [Chakra UI - Accordion](https://chakra-ui.com/docs/disclosure/accordion)
- [Figma](https://www.figma.com/file/6aJ3cfu2Yq5dxUQcNDkm6Y/Brink-Designs?node-id=34%3A2)
