### ISSUE TITLE
🔎 Address search functionality

### ISSUE THREAD

**Issue by ayanmallik** [hack4impact-uiuc/brink#28]
**Type**: client/api/full stack
**FOF**:  3

## Description
- Implement search functionality to retrieve the user's address
- Will be using MapQuest API to implement address autocomplete

## Screenshot
<img width="606" alt="image" src="https://user-images.githubusercontent.com/45826922/154870855-da5654c3-5727-4c50-93bd-fbe8ebd8898e.png">

## Todo

- [ ] Store MapQuest API in the client directory
- [ ] Create helper function in utils folder that takes in input string and returns list of places
- [ ] Integrate search functionality into landing page

## Links
- [MapQuest API](https://developer.mapquest.com/documentation/searchahead-api/get/)
- [Tutorial](https://www.tracylum.com/blog/2017-05-20-autocomplete-an-address-with-a-react-form/)
