### ISSUE TITLE
📍 Location Caching

### ISSUE THREAD

**Issue by amit-sawhney** [hack4impact-uiuc/brink#34]
**Type**: client
**FOF**:  3

## Description

Please reference #38 to figure out how this works.

Add a context and provider that the application can hook into that stores the address for the application. When a user enters their address on the landing page, it saves this in local storage and the context and redirects to the home page. 

Other pages should be able to hook into this information and display/access it as necessary. 

## Screenshot

<img width="1512" alt="Voter FAQ" src="https://user-images.githubusercontent.com/66758185/155857254-8d1d2265-fe99-4c69-8216-fa2666252eea.png">

## Todo

- [ ] Make Provider, Context, and hook
- [ ] Update the hook in the landing page 
- [ ]  Display information in navbar

## Links
- [Figma](https://www.figma.com/file/6aJ3cfu2Yq5dxUQcNDkm6Y/Brink-Designs?node-id=90%3A119)
- #38
