### ISSUE TITLE
🎤 Voice Search

### ISSUE THREAD

**Issue by amit-sawhney** [hack4impact-uiuc/brink#36]
**Type**: client/api/full stack
**FOF**:  3

## Description

Allow a user to search using their voice. This will require microphone access, parsing this input into the address search, and populating the selected address that comes back.

Edge cases:
- No location comes back: Don't populate anything, maybe a toast would be helpful
- Multiple places come back: choose the first potentially. 

_Note_: you don't need to physically "add/use/hit enter" on this address this address that is populated. Rather let the user press this button still. 

## Screenshot

<img width="180" alt="image" src="https://user-images.githubusercontent.com/66758185/155082513-1ae9a8b3-bfe5-428b-8b4b-b7c1050c12dc.png">

## Todo

- [ ] Create a useVoice Hook
- [ ] Parse this input into the google search api
- [ ] Handle edge cases

## Links
- [figma](https://www.figma.com/file/6aJ3cfu2Yq5dxUQcNDkm6Y/Brink-Designs)
- [Microphone Configuration](https://www.sitepoint.com/voice-search-react/)
