### ISSUE TITLE
🍞 Ballot Breadcrumb

### ISSUE THREAD

**Issue by ayanmallik** [hack4impact-uiuc/brink#47]
**Type**: client
**FOF**:  *TBD*

## Description
- Create the breadcrumb that tracks the user's location in respect to the overall election/specific race
- Each of these sections on the breadcrumb are hyperlinks that redirect to the spage

## Screenshot
<img width="667" alt="image" src="https://user-images.githubusercontent.com/45826922/157101071-9d701935-1fa6-44c4-8f46-d7dc897686aa.png">

## Todo

- [ ] Build the UI component for the ballot breadcrumb
- [ ] Set up the URL structure for the various races within an election
- [ ] Link to Favorite Candidates page

## Links
- [Figma](https://www.figma.com/file/6aJ3cfu2Yq5dxUQcNDkm6Y/Brink-Designs?node-id=34%3A2)
