### ISSUE TITLE
♿ Accessibility Modal

### ISSUE THREAD

**Issue by amit-sawhney** [hack4impact-uiuc/brink#61]
**Type**: client
**FOF**:  ❓ 

## Description

Improve the accessibility of the application by making the base text sizes and color scheme of the website customizable. This will require the ability to change the color mode by configuring the theme of the application properly at a high level and a component by component basis. Additionally will need a draggable input that acts as a multiplier for the websites base font sizes.

## Screenshot

<img width="296" alt="image" src="https://user-images.githubusercontent.com/45826922/164151757-0a7cbd81-9a5d-461e-b791-fd3294a824b7.png">

## Todo

- [ ] High Contrast color scheme 
- [ ] Draggable font size
- [ ] Global language setting? -- dependent on if Brink wants to support this in Contentful.

## Links
- [Chakra UI Color Mode](https://chakra-ui.com/docs/styled-system/features/color-mode)
- [Chakra UI Font Sizes](https://chakra-ui.com/docs/styled-system/features/text-and-layer-styles)
- [Chakra UI RTL](https://chakra-ui.com/docs/styled-system/features/rtl-support)
- [Figma](https://www.figma.com/file/6aJ3cfu2Yq5dxUQcNDkm6Y/Brink-Designs)
