### ISSUE TITLE
🎨 Configure Chakra UI themes

### ISSUE THREAD

**Issue by amit-sawhney** [hack4impact-uiuc/brink#68]
**Type**: client
**FOF**:  ❓ 

## Description

Setup the theme for the Brink's color pallet and font sizes for mobile, tablet, and desktop. Migrate away from having base hardcoded components with overridden styles and use the theming and variants properly. 

## Todo

- [ ] Create `theme` directory
- [ ] Create fonts file
- [ ] Create colors file
- [ ] Create a component file (maybe directory to store them all) for each component that we are going to theme (buttons, links, alerts, accordians)

## Links
- [Component theming in Chakra UI](https://chakra-ui.com/docs/styled-system/theming/component-style)
- [Figma](https://www.figma.com/file/6aJ3cfu2Yq5dxUQcNDkm6Y/Brink-Designs?node-id=34%3A2)
