### ISSUE TITLE
🤩 Favorite Candidates Page

### ISSUE THREAD

**Issue by ayanmallik** [hack4impact-uiuc/brink#72]
**Type**: client
**FOF**:  3

## Description
- Build out desktop and mobile pages to display Favorite Candidates
- Update the FavoriteCandidatesButton to store more information about the selected candidate (id, position, level)
- Parse the cached favorites to organize and present the favorite candidates for each race

You'll want to leverage and reuse various components from past PRs (for example, you'll want to refer to Sue's PR to build out the mobile support for the candidate links and you'll want to refer to Arman's PR to see how we count/display the number of candidates)

## Screenshot
<img width="657" alt="image" src="https://user-images.githubusercontent.com/45826922/160223906-b258a2bb-a5a3-4526-938e-8f9ccc7ac8f3.png">
<img width="276" alt="image" src="https://user-images.githubusercontent.com/45826922/160223927-07e3f255-d9fd-4168-bdbd-9060158d83b7.png">
<img width="111" alt="image" src="https://user-images.githubusercontent.com/45826922/160223942-b7502bfb-a78c-4072-801a-f41a59a7e0a3.png">

## Todo

- [x] Cache/Parse more information about the favorite candidates
- [x] Build out the Desktop view for the Favorite Candidates page
- [ ] Integrate mobile support for the Favorite Candidates page

## Links
- [Figma](https://www.figma.com/file/6aJ3cfu2Yq5dxUQcNDkm6Y/Brink-Designs?node-id=34%3A2)
- *Insert Sue's BallotLink here once merged*
- *Insert Arman's candidate counter here once merged*
