### ISSUE TITLE
🙋‍♀️ Help Page

### ISSUE THREAD

**Issue by ayanmallik** [hack4impact-uiuc/brink#73]
**Type**: client
**FOF**:  2

## Description
- Build out the mobile and desktop views for the help page
- Utilize various base UI components from Amit's PR (#65)

## Screenshot
<img width="665" alt="image" src="https://user-images.githubusercontent.com/45826922/160224259-ef93797e-d0eb-4c2b-bf7f-176ac36c46a7.png">
<img width="244" alt="image" src="https://user-images.githubusercontent.com/45826922/160224519-77e402fc-2239-4177-8a4b-5c531ffd3c05.png">

## Todo

- [ ] Build out a component that display the content for each resource
- [ ] Iterate through mock data to display list of resources under multiple sections
- [ ] Make the help page both desktop and mobile compatible

## Links
- [Figma](https://www.figma.com/file/6aJ3cfu2Yq5dxUQcNDkm6Y/Brink-Designs?node-id=34%3A2)
