### ISSUE TITLE
👨‍🎨  Restyle Ballot pages to match new figma designs

### ISSUE THREAD

**Issue by code-arman** [hack4impact-uiuc/brink#79]
**Type**: client/api/full stack
**FOF**:  1/2/3/5

## Description
Match the new figma designs on the Ballot page
## Screenshot
<img width="1120" alt="Screen Shot 2022-04-06 at 1 20 05 PM" src="https://user-images.githubusercontent.com/46976119/162042143-f2600690-e289-4f77-aa31-13b411aa96af.png">
<img width="965" alt="Screen Shot 2022-04-06 at 1 20 44 PM" src="https://user-images.githubusercontent.com/46976119/162042255-71f24d63-979c-4270-a3a6-e1efb2a46e10.png">

## Todo

- [x] Style CandidateCard, making them smaller, adding border, and including the View candidate strip on bottom
- [x] Style BallotTitle, making it aligned left on all pages
- [x] Add a component for the Election name with the cool border left thingy
- [x] Add borders for the BallotLinks 

## Links
- [figma](https://www.figma.com/file/6aJ3cfu2Yq5dxUQcNDkm6Y/Brink-Designs?node-id=565%3A1390)
