### ISSUE TITLE
✅ Integrate Election/Brink Data into Checklist

### ISSUE THREAD

**Issue by ayanmallik** [hack4impact-uiuc/brink#81]
**Type**: client
**FOF**:  3

## Description
- Utilize the selected voting methods and the data provided by Brink to populate the voting checklist

## Screenshot
Checklist for No Elections:
<img width="605" alt="image" src="https://user-images.githubusercontent.com/45826922/163694427-70beb2b7-2fe5-4d1a-a35d-9707a4f76bbd.png">

Checklist for Example Voting Method:
<img width="605" alt="image" src="https://user-images.githubusercontent.com/45826922/163694436-377fd573-5eec-49a0-bca9-c7c48907e1d1.png">

## Todo

- [ ] Pull Brink's collection of data for voting checklist items based on the selected method
- [ ] Integrate data into voting checklist
- [ ] Display default checklist when there's no upcoming election

## Links
- [Checklist Content](https://github.com/tablexi/brink-rn/blob/c44ea6e1ac2a01ea01240d96995c670383f701d0/src/localization/locales/en.ts)
- [Button Content](https://github.com/tablexi/brink-rn/blob/c44ea6e1ac2a01ea01240d96995c670383f701d0/fixtures/getElectionAuthorityJson.json)
