### ISSUE TITLE
📨 Create Voting Method Selection Page

### ISSUE THREAD

**Issue by ericcccsliu** [hack4impact-uiuc/brink#83]
**Type**: client
**FOF**:  3

## Description
Create voting method selection page
## Screenshot
<img width="764" alt="Screen Shot 2022-04-11 at 7 13 43 PM" src="https://user-images.githubusercontent.com/62641231/162853270-062f7b70-15c5-4a41-96c2-1839cb34490a.png">

## Todo

- [x] Create voting method selection buttons
- [x] Conditionally render buttons based on valid voting methods from Contentful
- [x] Create context for selected voting method 
- [x] Use useElections hook to display current election card 
- [x] Style according to figma

## Links
- [figma](https://www.figma.com/file/6aJ3cfu2Yq5dxUQcNDkm6Y/Brink-Designs?node-id=34%3A2)
