### ISSUE TITLE
🙋‍♀️ Help Page

### ISSUE THREAD

**Issue by ayanmallik** [hack4impact-uiuc/brink#90]
**Type**: client
**FOF**:  3

## Description
- Populate various resources on the help page
    - Get Help Now Links/Contacts
    - Resolve Polling Place Issues
    - About Brink
- Utilize the mobile help screen as a guide: https://github.com/tablexi/brink-rn/blob/c44ea6e1ac2a01ea01240d96995c670383f701d0/src/screens/Help/view.tsx

## Screenshot
<img width="672" alt="image" src="https://user-images.githubusercontent.com/45826922/163880563-752249be-f216-4831-912d-334ce4d79643.png">
<img width="188" alt="image" src="https://user-images.githubusercontent.com/45826922/163882207-40668b49-7d83-4a91-a5e6-7fbf3e92e0d3.png">

## Todo

- [ ] Build out UI components for inner contents within the help page
- [ ] Fill out the contents within the help page
- [ ] Ensure that the page is mobile-responsive

## Links
- [Figma](https://www.figma.com/file/6aJ3cfu2Yq5dxUQcNDkm6Y/Brink-Designs?node-id=565%3A1390)
- [Mobile Help Screen](https://github.com/tablexi/brink-rn/blob/c44ea6e1ac2a01ea01240d96995c670383f701d0/src/screens/Help/view.tsx)
